export const ALL_EVENT_REQUEST = "ALL_EVENT_REQUEST";
export const ALL_EVENT_SUCCESS = "ALL_EVENT_SUCCESS";
export const ALL_EVENT_FAIL = "ALL_EVENT_FAIL";


export const EVENT_DETAILS_REQUEST = "EVENT_DETAILS_REQUEST";
export const EVENT_DETAILS_SUCCESS = "EVENT_DETAILS_SUCCESS";
export const EVENT_DETAILS_FAIL = "EVENT_DETAILS_FAIL";
export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST";
export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS";
export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET";
export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL";
export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST";
export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS";
export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET";
export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL";

export const NEW_EVENT_REQUEST = "NEW_EVENT_REQUEST";
export const NEW_EVENT_SUCCESS = "NEW_EVENT_SUCCESS";
export const NEW_EVENT_RESET = "NEW_EVENT_RESET";
export const NEW_EVENT_FAIL = "NEW_EVENT_FAIL";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_RESET = "DELETE_EVENT_RESET";
export const DELETE_EVENT_FAIL = "DELETE_EVENT_FAIL";

export const UPDATE_EVENT_REQUEST = "UPDATE_EVENT_REQUEST";
export const UPDATE_EVENT_SUCCESS = "UPDATE_EVENT_SUCCESS";
export const UPDATE_EVENT_RESET = "UPDATE_EVENT_RESET";
export const UPDATE_EVENT_FAIL = "UPDATE_EVENT_FAIL";

export const ADMIN_EVENT_REQUEST = "ADMIN_EVENT_REQUEST";
export const ADMIN_EVENT_SUCCESS = "ADMIN_EVENT_SUCCESS";
export const ADMIN_EVENT_FAIL = "ADMIN_EVENT_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";